apiVersion: v1
kind: ReplicationController
metadata:
  name: stolon-keeper-rc
spec:
  replicas: 1
  selector:
    name: stolon-keeper
  template:
    metadata:
      labels:
        name: stolon-keeper
        stolon-cluster: "kube-stolon"
        stolon-keeper: "true"
    spec:
      containers:
      - name: stolon-keeper
        image: sorintlab/stolon:master
        env:
          - name: KEEPER
            value: "true"
          - name: STKEEPER_CLUSTER_NAME
          # TODO(sgotti) Get cluster name from "stoloncluster" label using a downward volume api instead of duplicating the name here
            value: "kube-stolon"
          - name: STKEEPER_ETCD_ENDPOINTS
            value: "http://10.245.1.1:4001"
            # Enable debugging
          - name: STKEEPER_DEBUG
            value: "true"
        ports:
          - containerPort: 5431
          - containerPort: 5432
        volumeMounts:
        - mountPath: /stolon-data
          name: data
      volumes:
        - name: data
          emptyDir: {}
