apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stolon-sentinel
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: stolon-sentinel
        stolon-cluster: kube-stolon
    spec:
      containers:
      - name: stolon-sentinel
        image: sorintlab/stolon:master-pg9.6
        command:
          - "/bin/bash"
          - "-ec"
          - |
            exec gosu stolon stolon-sentinel
        env:
          # TODO(sgotti) Get cluster name from "stolon-cluster" label using a downward volume api instead of duplicating the name here
          - name: STSENTINEL_CLUSTER_NAME
            value: "kube-stolon"
          - name: STSENTINEL_STORE_BACKEND
            value: "etcdv3" # Or: etcdv2, consul
          - name: STSENTINEL_STORE_ENDPOINTS
            value: "http://192.168.122.1:2379"
          ## Uncomment this to enable debug logs
          #- name: STSENTINEL_DEBUG
          #  value: "true"
