apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stolon-proxy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: stolon-proxy
        stolon-cluster: kube-stolon
    spec:
      containers:
      - name: stolon-proxy
        image: sorintlab/stolon:master-pg9.6
        command:
          - "/bin/bash"
          - "-ec"
          - |
            exec gosu stolon stolon-proxy
        env:
          # TODO(sgotti) Get cluster name from "stolon-cluster" label using a downward volume api instead of duplicating the name here
          - name: STPROXY_CLUSTER_NAME
            value: "kube-stolon"
          - name: STPROXY_STORE_BACKEND
            value: "etcdv3" # Or: etcdv2, consul
          - name: STPROXY_STORE_ENDPOINTS
            value: "http://192.168.122.1:2379"
          - name: STPROXY_LISTEN_ADDRESS
            value: "0.0.0.0"
          ## Uncomment this to enable debug logs
          #- name: STPROXY_DEBUG
          #  value: "true"
        ports:
          - containerPort: 5432
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 10
          timeoutSeconds: 5
