apiVersion: v1
kind: ReplicationController
metadata:
  name: stolon-sentinel
spec:
  replicas: 2
  selector:
    name: stolon-sentinel
  template:
    metadata:
      labels:
        name: stolon-sentinel
        stolon-cluster: "kube-stolon"
        stolon-sentinel: "true"
    spec:
      containers:
      - name: stolon-sentinel
        image: sorintlab/stolon:v0.8.0-pg9.6
        command:
          - "/bin/bash"
          - "-ec"
          - |
            exec gosu stolon stolon-sentinel
        env:
          - name: STSENTINEL_CLUSTER_NAME
            value: "kube-stolon"
          - name: STSENTINEL_STORE_BACKEND
            value: "etcdv3" # Or: etcdv2, consul
          - name: STSENTINEL_STORE_ENDPOINTS
            value: "http://192.168.122.1:2379"
          ## Uncomment this to enable debug logs
          #- name: STSENTINEL_DEBUG
          #  value: "true"
