[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.2.11"

[[constraint]]
  name = "github.com/docker/leadership"
  version = "0.1.0"

[[constraint]]
  name = "github.com/docker/libkv"
  version = "0.2.1"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "0.0.3"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/sgotti/gexpect"

[[constraint]]
  branch = "master"
  name = "github.com/sorintlab/pollon"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.4.1"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.3.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
