[[constraint]]
  name = "github.com/spf13/cobra"
  revision = "de2d9c4eca8f3c1de17d48b096b6504e0296f003"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.2.11"

[[constraint]]
  name = "github.com/docker/leadership"
  version = "0.1.0"

[[constraint]]
  name = "github.com/docker/libkv"
  version = "0.2.1"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "0.0.3"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/sgotti/gexpect"

[[constraint]]
  branch = "master"
  name = "github.com/sorintlab/pollon"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.4.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.8.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.8.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.8.2"

## Required for
## https://github.com/kubernetes/client-go/blob/059133e3e3ab5ede57dea5063a16b3fdc729b64f/tools/clientcmd/client_config.go#L160
## that relies on an old mergo version behavior
[[override]]
  name = "github.com/imdario/mergo"
  revision = "6633656539c1639d9d78127b7d47c622b5d7b6dc"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
